blank_issues_enabled: false
contact_links:
  - name: Project Discussions Forum
    url: https://test.com
    about: Please direct questions, ideas/feature requests, and other discussions to the Discussions Forum.
