blank_issues_enabled: true
contact_links:
  - name: Project Discussions Forum
    url: /discussions
    about: Please direct questions, ideas/feature requests, and other discussions to the Discussions Forum.
