name: "Build <app> on Push"
on:
  push:
    paths:
      - ".github/workflows/*-<app>-*.yml"
      - "apps/<app>/**"
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        required: true
        default: "main"

jobs:
  build-<app>:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
