name: "Deploy <app> on Main"
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

jobs:
  build-<app>:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
